kotlin.code.style=official
# Выделение оперативной памяти для Gradle (поставьте 4G или 6G в зависимости от вашего ПК)
org.gradle.jvmargs=-Xmx6g -XX:+UseParallelGC -Dfile.encoding=UTF-8
# Включение демона Gradle (он остается в памяти и не стартует с нуля)
org.gradle.daemon=true
# Параллельная сборка независимых модулей
org.gradle.parallel=true
# Включение кэширования сборки между запусками
org.gradle.caching=true
# Инкрементальная компиляция для Kotlin
kotlin.incremental=true
# 5. Оптимизирует инкрементальную сборку при использовании KSP (если используете).
ksp.incremental=true